### ISSUE TITLE
我的grub里没有theme文件夹

### ISSUE THREAD

**Issue by StevenIIV** [LordShenron/Grub-Themes#3]

**Comment by LordShenron** [comment]
English please so i can understand :)

**Comment by StevenIIV** [comment]
fine ,I am a newbie of Ubuntu. I can't find the "theme" folder from grub
so shall I need create a new?

**Comment by LordShenron** [comment]
Create a "themes" folder in /boot/grub if its not there

**Comment by StevenIIV** [comment]
right click to create a new folder option is grey, Now I have created by terminal
thanks

**Comment by LordShenron** [comment]
You have to open your file manager with administrative access.
